In [1]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("D:\\Projects\\bridge-optimization\\data\\optimization_dataset.csv")

In [4]:
df.head()

,span_m,carriageway_width_m,include_median,footpath,skew_angle_deg,index,round,gen,n,spacing_m,...,D_mm,bf_mm,tf_mm,tw_mm,dw_mm,steel_kN,deck_kN,total_kN,feasible,status
0,20.0,4.25,No,NaN,0.0,1,Initial,0,2,2.575,...,1320.0,295.0,45.0,22.0,1230.0,168.3,579.4,747.7,0,FAIL
1,20.0,4.25,No,NaN,0.0,2,Initial,0,2,2.575,...,1050.0,260.0,56.0,12.0,938.0,126.8,566.5,693.3,0,FAIL
2,20.0,4.25,No,NaN,0.0,3,Initial,0,2,2.575,...,1220.0,375.0,80.0,36.0,1060.0,308.2,386.2,694.5,0,FAIL
3,20.0,4.25,No,NaN,0.0,4,Initial,0,2,2.575,...,1160.0,385.0,80.0,10.0,1000.0,224.8,463.5,688.3,0,FAIL
4,20.0,4.25,No,NaN,0.0,5,Initial,0,2,2.575,...,1180.0,285.0,100.0,36.0,980.0,289.8,618.0,907.8,0,FAIL

In [5]:
df.tail()

,span_m,carriageway_width_m,include_median,footpath,skew_angle_deg,index,round,gen,n,spacing_m,...,D_mm,bf_mm,tf_mm,tw_mm,dw_mm,steel_kN,deck_kN,total_kN,feasible,status
20195,30.0,4.25,No,NaN,0.0,196,Gen 3,3,5,1.030,...,2000.0,595.0,100.0,40.0,1800.0,2249.0,811.1,3060.2,1,PASS
20196,30.0,4.25,No,NaN,0.0,197,Gen 3,3,5,1.030,...,1610.0,370.0,16.0,8.0,1578.0,288.1,811.1,1099.2,0,FAIL
20197,30.0,4.25,No,NaN,0.0,198,Gen 3,3,4,1.288,...,1220.0,355.0,28.0,40.0,1164.0,625.9,946.3,1572.2,0,FAIL
20198,30.0,4.25,No,NaN,0.0,199,Gen 3,3,4,1.288,...,1860.0,730.0,8.0,36.0,1844.0,735.4,772.5,1507.9,1,PASS
20199,30.0,4.25,No,NaN,0.0,200,Gen 3,3,5,1.030,...,1360.0,425.0,12.0,36.0,1336.0,686.4,811.1,1497.6,0,FAIL

In [6]:
df.describe()

,span_m,carriageway_width_m,footpath,skew_angle_deg,index,gen,n,spacing_m,t_slab_mm,D_mm,bf_mm,tf_mm,tw_mm,dw_mm,steel_kN,deck_kN,total_kN,feasible
count,20200.000000,20200.00,0.0,20200.0,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000,20200.000000
mean,25.000000,4.25,NaN,0.0,100.500000,1.500000,3.505545,1.599864,194.092079,1313.039604,406.060891,59.647723,22.830149,1193.744158,538.559851,624.792035,1163.351356,0.356733
std,2.915548,0.00,NaN,0.0,57.735734,1.118062,0.952544,0.501238,34.889618,276.590725,101.505967,34.192054,11.993162,268.495204,373.424101,134.852758,430.385563,0.479047
min,20.000000,4.25,NaN,0.0,1.000000,0.000000,2.000000,1.030000,150.000000,800.000000,160.000000,6.000000,6.000000,600.000000,22.800000,386.200000,421.900000,0.000000
25%,22.500000,4.25,NaN,0.0,50.750000,0.750000,3.000000,1.288000,160.000000,1100.000000,335.000000,25.000000,12.000000,990.000000,271.100000,520.900000,853.300000,0.000000
50%,25.000000,4.25,NaN,0.0,100.500000,1.500000,4.000000,1.288000,190.000000,1290.000000,395.000000,63.000000,22.000000,1170.000000,437.950000,609.100000,1081.950000,0.000000
75%,27.500000,4.25,NaN,0.0,150.250000,2.250000,4.000000,1.717000,225.000000,1510.000000,470.000000,90.000000,36.000000,1380.000000,709.400000,718.400000,1382.025000,1.000000
max,30.000000,4.25,NaN,0.0,200.000000,3.000000,5.000000,2.575000,250.000000,2000.000000,785.000000,100.000000,40.000000,1988.000000,2615.200000,965.600000,3218.700000,1.000000

In [7]:
df.isnull().sum()

span_m                     0
carriageway_width_m        0
include_median             0
footpath               20200
skew_angle_deg             0
index                      0
round                      0
gen                        0
n                          0
spacing_m                  0
t_slab_mm                  0
D_mm                       0
bf_mm                      0
tf_mm                      0
tw_mm                      0
dw_mm                      0
steel_kN                   0
deck_kN                    0
total_kN                   0
feasible                   0
status                     0
dtype: int64